<!DOCTYPE html>
<html lang="ja">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" >
    <script type="text/javascript" src="../../js/fixed_midashi.js"></script>
    <title><?= sprintf(_('about %s attendance'), $title) ?></title>
    <link type="text/css" rel="stylesheet" href="../../css/calendar.css" />
</head>
<body>
    <h1>出勤表について</h1>
    <p>
        エミュリボンのキャスト出勤を、Twitterの情報などを元に非公式にまとめたものです。
        管理はLINE内のBOTで行っており、友だちに追加してメッセージ送信することで、誰でも登録・修正が可能です。
        グループに誘うことでグループトークで使用することもできます。
    </p>
    <p>
        詳しい操作方法は、LINEアカウントのホーム投稿を参照ください。
    </p>
    <a href="https://line.me/R/ti/p/%40qdx5580n"><img height="36" border="0" alt="友だち追加" src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png"></a>

    <p>
        問い合わせ、改善提案、クレーム、誹謗中傷などは<a href="https://twitter.com/kazy111">じゃわてぃー</a>迄。
    </p>
</body>
</html>
